# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request_target:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.sha }}"
